export type Category = "all" | "field" | "personal" | "creative";

export type BizType = {
  id: string;
  name: string;
  tagline: string;
  emoji: string;
  gradient: string;
  category: Category;
  demo?: string;
  features: string[];
};

const defaultFieldFeatures    = ["Service area pages", "Quote request form", "Lead capture CRM"];
const defaultPersonalFeatures = ["Service menu & pricing", "Booking / contact flow", "Team profiles"];
const defaultCreativeFeatures = ["Portfolio gallery", "Package tiers", "Inquiry / booking form"];

export const businesses: BizType[] = [
  // ── Field Service ────────────────────────────────────────────
  {
    id: "pressure-washing",
    name: "Pressure Washing",
    tagline: "Lead capture, trust signals, before/after results",
    emoji: "💧",
    gradient: "from-[#063b4e] to-[#085272]",
    category: "field",
    demo: "/samples/pressure-washing",
    features: ["Before & after gallery", "Instant quote request form", "Service area + Google Maps ready"],
  },
  {
    id: "landscaping",
    name: "Landscaping & Lawn Care",
    tagline: "Seasonal promos, service packages, quote forms",
    emoji: "🌿",
    gradient: "from-emerald-800 to-green-700",
    category: "field",
    demo: "/samples/landscaping",
    features: ["Seasonal promo sections", "Service package pricing", "Recurring maintenance upsell"],
  },
  {
    id: "painting",
    name: "Painting",
    tagline: "Gallery-first layout built for residential conversions",
    emoji: "🎨",
    gradient: "from-slate-800 to-slate-700",
    category: "field",
    demo: "/samples/painting",
    features: ["Before & after project gallery", "Interior vs. exterior sections", "Free estimate CTA"],
  },
  {
    id: "roofing",
    name: "Roofing",
    tagline: "Insurance claim support, free inspection CTAs",
    emoji: "🏠",
    gradient: "from-[#1e2d40] to-[#2a3d57]",
    category: "field",
    demo: "/samples/roofing",
    features: ["Storm damage + insurance copy", "Free inspection form", "Warranty trust signals"],
  },
  {
    id: "cleaning",
    name: "Home Cleaning",
    tagline: "Recurring booking, eco-friendly trust badges",
    emoji: "✨",
    gradient: "from-sky-600 to-sky-800",
    category: "field",
    demo: "/samples/cleaning",
    features: ["Recurring booking upsell", "Eco-friendly badge section", "Move-in / deep clean packages"],
  },
  {
    id: "hvac",
    name: "HVAC",
    tagline: "Emergency CTAs, seasonal filters, maintenance plans",
    emoji: "❄️",
    gradient: "from-blue-700 to-blue-900",
    category: "field",
    demo: "/samples/hvac",
    features: ["24/7 emergency CTA", "Seasonal maintenance plans", "Finance options section"],
  },
  {
    id: "plumbing",
    name: "Plumbing",
    tagline: "24/7 emergency framing, fast scheduling flow",
    emoji: "🔧",
    gradient: "from-orange-600 to-orange-800",
    category: "field",
    demo: "/samples/plumbing",
    features: ["Emergency call button", "Fast scheduling form", "Licensed & insured trust bar"],
  },
  {
    id: "electrical",
    name: "Electrical",
    tagline: "Licensed & bonded trust signals, service area map",
    emoji: "⚡",
    gradient: "from-yellow-600 to-amber-700",
    category: "field",
    features: defaultFieldFeatures,
  },
  {
    id: "window-cleaning",
    name: "Window Cleaning",
    tagline: "Residential & commercial, before/after gallery",
    emoji: "🪟",
    gradient: "from-cyan-700 to-sky-800",
    category: "field",
    features: ["Residential & commercial split", "Before/after gallery", "Quote request form"],
  },
  {
    id: "junk-removal",
    name: "Junk Removal",
    tagline: "Same-day booking, upfront pricing, before/after",
    emoji: "🗑️",
    gradient: "from-amber-700 to-orange-700",
    category: "field",
    features: ["Same-day availability CTA", "Upfront pricing guide", "Item type checklist"],
  },
  {
    id: "tree-service",
    name: "Tree Service",
    tagline: "Free estimates, storm damage response, safety trust",
    emoji: "🌳",
    gradient: "from-green-800 to-emerald-900",
    category: "field",
    features: ["Storm damage response section", "Free estimate form", "Insurance & safety trust signals"],
  },
  {
    id: "pest-control",
    name: "Pest Control",
    tagline: "Service plan upsells, same-day guarantees",
    emoji: "🐛",
    gradient: "from-red-700 to-rose-800",
    category: "field",
    features: ["Pest type service pages", "Monthly plan upsell", "Same-day guarantee CTA"],
  },
  {
    id: "pool-service",
    name: "Pool Service",
    tagline: "Weekly maintenance plans, chemical service packages",
    emoji: "🏊",
    gradient: "from-blue-500 to-cyan-700",
    category: "field",
    features: ["Weekly maintenance plans", "Chemical service packages", "Opening / closing seasonal CTAs"],
  },
  {
    id: "handyman",
    name: "Handyman",
    tagline: "Broad service list, quick quote form, local trust",
    emoji: "🔨",
    gradient: "from-stone-700 to-stone-800",
    category: "field",
    features: defaultFieldFeatures,
  },
  {
    id: "concrete",
    name: "Concrete & Flatwork",
    tagline: "Project gallery, free estimate, service area",
    emoji: "🧱",
    gradient: "from-slate-600 to-slate-800",
    category: "field",
    features: ["Project gallery", "Free estimate form", "Residential & commercial sections"],
  },
  {
    id: "fencing",
    name: "Fencing",
    tagline: "Material options, fence gallery, fast quote",
    emoji: "🏡",
    gradient: "from-amber-800 to-yellow-900",
    category: "field",
    features: ["Material options section", "Project gallery", "Fast quote request form"],
  },
  {
    id: "gutter",
    name: "Gutter Services",
    tagline: "Cleaning, guards, repair — seasonal upsell focus",
    emoji: "🌧️",
    gradient: "from-slate-700 to-slate-900",
    category: "field",
    features: ["Seasonal cleaning CTAs", "Guard installation upsell", "Free inspection form"],
  },
  {
    id: "solar",
    name: "Solar Installation",
    tagline: "Savings calculator, financing, local incentives",
    emoji: "☀️",
    gradient: "from-amber-500 to-orange-600",
    category: "field",
    features: ["Savings estimate section", "Financing & incentives copy", "Free assessment CTA"],
  },

  // ── Personal Service ──────────────────────────────────────────
  {
    id: "barbershop",
    name: "Barbershop",
    tagline: "Pricing menu, walk-in hours, team profiles",
    emoji: "✂️",
    gradient: "from-slate-900 to-slate-800",
    category: "personal",
    demo: "/samples/barbershop",
    features: ["Service & pricing menu", "Barber team profiles", "Walk-in hours + booking link"],
  },
  {
    id: "hair-salon",
    name: "Hair Salon",
    tagline: "Services & pricing, team gallery, online booking",
    emoji: "💇",
    gradient: "from-pink-700 to-rose-800",
    category: "personal",
    features: ["Stylist team gallery", "Service & pricing menu", "Booking integration CTA"],
  },
  {
    id: "nail-salon",
    name: "Nail Salon",
    tagline: "Gallery, service menu, appointment booking",
    emoji: "💅",
    gradient: "from-purple-700 to-violet-800",
    category: "personal",
    features: ["Nail art gallery", "Service menu & pricing", "Appointment booking link"],
  },
  {
    id: "personal-trainer",
    name: "Personal Training",
    tagline: "Transformation gallery, packages, free consult CTA",
    emoji: "💪",
    gradient: "from-red-700 to-rose-700",
    category: "personal",
    features: ["Transformation gallery", "Training package tiers", "Free consult CTA"],
  },
  {
    id: "massage",
    name: "Massage Therapy",
    tagline: "Service menu, calm design, easy appointment flow",
    emoji: "🧘",
    gradient: "from-violet-700 to-purple-900",
    category: "personal",
    features: defaultPersonalFeatures,
  },
  {
    id: "tattoo",
    name: "Tattoo Studio",
    tagline: "Artist portfolios, flash gallery, booking consult",
    emoji: "🖋️",
    gradient: "from-slate-950 to-zinc-800",
    category: "personal",
    features: ["Artist portfolio pages", "Flash gallery", "Booking consult request form"],
  },
  {
    id: "dog-grooming",
    name: "Dog Grooming",
    tagline: "Service packages, breed-specific pricing, booking",
    emoji: "🐾",
    gradient: "from-teal-700 to-cyan-800",
    category: "personal",
    features: ["Breed-friendly pricing guide", "Grooming packages", "Appointment booking"],
  },
  {
    id: "esthetician",
    name: "Esthetician / Spa",
    tagline: "Treatment menu, memberships, online booking",
    emoji: "🌸",
    gradient: "from-rose-600 to-pink-700",
    category: "personal",
    features: ["Treatment menu", "Membership / package tiers", "Online booking link"],
  },
  {
    id: "gym",
    name: "Gym / Fitness Studio",
    tagline: "Class schedule, membership plans, free trial CTA",
    emoji: "🏋️",
    gradient: "from-slate-800 to-zinc-900",
    category: "personal",
    features: ["Class schedule section", "Membership plan tiers", "Free trial / day pass CTA"],
  },

  // ── Creative & Events ─────────────────────────────────────────
  {
    id: "photography",
    name: "Photography",
    tagline: "Portfolio-first, package pricing, inquiry flow",
    emoji: "📸",
    gradient: "from-zinc-800 to-slate-900",
    category: "creative",
    features: ["Full-width portfolio gallery", "Package & pricing tiers", "Inquiry / booking form"],
  },
  {
    id: "catering",
    name: "Catering & Food Trucks",
    tagline: "Menu preview, event booking, social proof",
    emoji: "🍽️",
    gradient: "from-orange-700 to-red-700",
    category: "creative",
    features: ["Menu preview section", "Event & corporate booking", "Reviews & social proof"],
  },
  {
    id: "dj",
    name: "DJ & Events",
    tagline: "Mix samples, package tiers, event inquiry form",
    emoji: "🎵",
    gradient: "from-violet-800 to-purple-900",
    category: "creative",
    features: ["Audio / video samples", "Package tiers", "Event inquiry form"],
  },
  {
    id: "tutoring",
    name: "Tutoring & Coaching",
    tagline: "Subject list, session packages, parent trust signals",
    emoji: "📚",
    gradient: "from-blue-700 to-indigo-800",
    category: "creative",
    features: ["Subject / topic list", "Session packages & pricing", "Results & parent testimonials"],
  },
  {
    id: "video",
    name: "Video Production",
    tagline: "Reel showcase, package tiers, fast quote",
    emoji: "🎬",
    gradient: "from-slate-800 to-zinc-900",
    category: "creative",
    features: defaultCreativeFeatures,
  },
  {
    id: "florist",
    name: "Florist",
    tagline: "Arrangement gallery, event packages, same-day delivery",
    emoji: "💐",
    gradient: "from-pink-600 to-rose-700",
    category: "creative",
    features: ["Arrangement gallery", "Wedding & event packages", "Same-day delivery CTA"],
  },
];

// Single source of truth for both the marketplace page and the homepage count CTA.
// Derives from the array above — adding or removing a business type automatically
// updates every page that imports this constant.
export const BUSINESS_TYPE_COUNT = businesses.length;
