import type { IndustryBlueprint } from "./types";

export const BLUEPRINTS: IndustryBlueprint[] = [

  // ── 1. Ice Cream / Food ──────────────────────────────────────────
  {
    id: "ice-cream-shop",
    industryName: "Ice Cream / Food",
    aliases: ["ice cream", "dessert", "gelato", "frozen yogurt", "creamery", "sweetshop", "candy"],
    recommendedStylePacks: ["playful-bright", "high-energy", "clean-pro"],
    activeSectionOrder: [
      "CustomIceCreamHero",
      "AnimatedStats",
      "ServicesShowcase",
      "GalleryMasonry",
      "ReviewsCarousel",
      "FooterPremium",
    ],
    plannedSections: [
      { type: "MenuShowcase",     label: "Flavor Board / Menu",      description: "Visual menu with flavor photos, allergen info, and seasonal tags",   priority: "high"   },
      { type: "SeasonalSpecials", label: "Seasonal Specials",        description: "Rotating limited-time flavors and offerings",                         priority: "high"   },
      { type: "CateringSection",  label: "Catering & Events",        description: "Event catering, birthday party packages, scoop-truck bookings",       priority: "medium" },
      { type: "HoursLocation",    label: "Hours & Location",         description: "Store hours with holiday exceptions and embedded map",                priority: "high"   },
      { type: "OnlineOrdering",   label: "Online Pre-Order",         description: "Pre-order for pickup or local delivery integration",                  priority: "medium" },
    ],
    optionalPremiumSections: ["FAQAccordion", "WhyChooseUs", "FinalCTA"],
    experimentalConcepts: [
      { id: "FlavorRevealCard",    concept: "Today's Flavor Reveal",      description: "Swipeable card that reveals the flavor of the day with a satisfying animation — updated by the owner each morning." },
      { id: "LoyaltyPunchCard",    concept: "Digital Loyalty Punch Card",  description: "Animated punch card that fills up as a returning customer — visual incentive that makes them want to come back."   },
      { id: "FlavorsCountdown",    concept: "Seasonal Flavor Countdown",   description: "Countdown timer for when a seasonal flavor drops or sells out — creates urgency and FOMO."                        },
      { id: "ScoopBuilderWidget",  concept: "Build Your Scoop",            description: "Interactive scoop builder — pick cone type, flavor, toppings — outputs a visual preview and estimated price."     },
    ],
    animationIdeas: [
      "Melting drip effect on scroll-enter for section dividers",
      "Sprinkle confetti burst on CTA button click",
      "Animated cone filling with color on page load",
      "Soft bounce on flavor tag hover",
      "Parallax layered ice cream photography background",
    ],
    contentInputIdeas: [
      "Photos of today's flavors (owner-uploadable)",
      "Full flavor menu list with prices",
      "Storefront exterior photo",
      "Staff serving customers photo",
      "Seasonal special announcement text",
      "Catering menu or event packages PDF",
      "Hours of operation",
    ],
    designNotes: "Lead with color and joy. Warm pink/peach gradients, soft shadows, rounded everything. Heavy on food photography. Playful typography with weight variation. Every section should feel like summer on a warm day. Use the playful-bright style pack as the default — it was designed for this industry.",
    recommendedCustomModules: ["CustomIceCreamHero", "GalleryMasonry"],
    importantBusinessFields: ["businessName", "city", "phone", "services", "businessDescription"],
    mediaNeeds: ["storefront photo", "flavor/product close-ups", "staff serving customers", "interior ambiance", "seasonal specials banner"],
    trustProofNeeds: ["years open", "flavors available", "awards or press mentions", "local community involvement"],
    ctaStrategy: "Visit us today or pre-order for pickup. Location and hours are primary conversion points.",
    quoteOrBookingNeeds: "Contact form for catering inquiries. Pre-order link when available.",
    menuOrPricingNeeds: true,
    aiPromptNotes: "Fun, warm, community-focused tone. Emphasize freshness, local ingredients, and seasonal variety. Avoid corporate language. Make people crave it.",
    content: {
      heroHeadlineTemplate: "Scoops That Make {city} Smile",
      heroSubheadlineTemplate: "{businessName} — handcrafted flavors made fresh daily in {city}.",
      heroCtaText: "See Today's Flavors",
      heroBadgeTemplate: "Fresh Made Daily · {city}",
      servicesHeading: "Our Flavors & Specialties",
      servicesSubheadline: "Made fresh daily with real ingredients. No shortcuts, ever.",
      defaultServices: [
        { icon: "🍦", title: "Classic Scoops",     description: "Single and double scoops in a cup or cone — rotating daily flavors." },
        { icon: "🎂", title: "Ice Cream Cakes",    description: "Custom ice cream cakes for birthdays, events, and celebrations." },
        { icon: "🍧", title: "Sundaes & Parfaits", description: "Build-your-own sundaes with fresh toppings and warm sauces." },
        { icon: "🌱", title: "Dairy-Free Options", description: "Oat milk and coconut milk-based flavors — just as creamy, just as delicious." },
      ],
      statsDefaults: [
        { value: "40+",  label: "Rotating Flavors" },
        { value: "4.9★", label: "Customer Rating"  },
        { value: "Daily",label: "Fresh Made"       },
        { value: "100%", label: "Real Ingredients" },
      ],
      whyReasons: [
        { icon: "🍦", title: "Made Fresh Daily",        description: "Every flavor crafted from scratch each morning. No frozen tubs, ever."                  },
        { icon: "🌿", title: "Real Ingredients",        description: "Local dairy, seasonal fruits, and zero artificial fillers. You can taste the difference." },
        { icon: "🎂", title: "Catering & Events",       description: "Bring the scoop truck to your party, wedding, or corporate event."                      },
        { icon: "🌈", title: "Something for Everyone",  description: "Dairy-free, vegan, nut-free, and classic options — everyone gets a scoop."              },
        { icon: "🏡", title: "Local & Community First", description: "We source locally and give back to the {city} community every season."                  },
      ],
      reviewsHeading: "What Our Customers Are Saying",
      reviewsDefaults: [
        { name: "Sarah M.", rating: 5, text: "Best ice cream I've had — and I don't say that lightly. The flavors are creative, fresh, and you can tell they care about every scoop." },
        { name: "James T.", rating: 5, text: "We came once and immediately told everyone we knew. My kids ask to come back every single week now." },
        { name: "Linda R.", rating: 5, text: "The dairy-free options are just as good as the regular flavors — maybe better. Finally a place where everyone in our family gets something they love." },
      ],
      faqDefaults: [
        { question: "Do you have dairy-free or vegan options?",     answer: "Yes! We offer a rotating selection of oat milk and coconut milk-based flavors. Ask at the counter for today's options." },
        { question: "Can I order a cake or book for an event?",     answer: "Absolutely. We do custom cakes, catering packages, and pre-orders. Contact us at least a week in advance."             },
        { question: "What are your hours?",                         answer: "We're open daily. Hours are posted on our front door and our Google listing."                                          },
        { question: "Do you offer sugar-free options?",             answer: "We carry reduced-sugar options depending on the season. Ask our team for what's available today."                     },
      ],
      finalCtaHeading: "Come In for a Scoop Today",
      finalCtaSubheading: "Life is better with ice cream. Come see what's fresh at {businessName}.",
      finalCtaText: "See Today's Flavors",
    },
  },

  // ── 2. Gym / Fitness Studio ──────────────────────────────────────
  {
    id: "gym-fitness",
    industryName: "Gym / Fitness Studio",
    aliases: ["gym", "fitness studio", "crossfit", "bootcamp", "martial arts", "yoga studio", "pilates", "fitness center", "fitness", "muay thai", "bjj", "boxing"],
    recommendedStylePacks: ["high-energy", "bold-contractor", "luxury-dark"],
    activeSectionOrder: [
      "HeroAnimated",
      "AnimatedStats",
      "ServicesShowcase",
      "WhyChooseUs",
      "ReviewsCarousel",
      "FAQAccordion",
      "FinalCTA",
      "FooterPremium",
    ],
    plannedSections: [
      { type: "ClassSchedule",         label: "Class Schedule",           description: "Weekly schedule with times, class types, and instructor names",        priority: "high"   },
      { type: "MembershipPricing",     label: "Membership Plans",         description: "Tiered membership pricing with feature comparison table",              priority: "high"   },
      { type: "TransformationGallery", label: "Transformation Gallery",   description: "Member before/after results with consent-gated testimonials",          priority: "high"   },
      { type: "TeamProfiles",          label: "Trainers & Coaches",       description: "Staff profiles with credentials, specialties, and headshots",          priority: "medium" },
      { type: "BookingCTA",            label: "Free Trial Class Booking", description: "Inline booking widget for a free trial class — low commitment entry",  priority: "high"   },
    ],
    optionalPremiumSections: ["GalleryMasonry"],
    experimentalConcepts: [
      { id: "LiveScheduleWidget",     concept: "Living Class Schedule",        description: "Class schedule that auto-marks past sessions and highlights what's coming up next — updated from a simple spreadsheet or CSV."     },
      { id: "TransformationTimeline", concept: "Member Transformation Wall",   description: "Photo grid of member before/afters with their story and duration — social proof at scale, protected behind consent gating."      },
      { id: "FitnessCalculator",      concept: "Goal Calculator",              description: "Simple quiz (goal + current fitness level) → recommended program + call-to-action. Personalizes the offer without a sales call."  },
      { id: "VirtualTour",            concept: "Virtual Gym Tour",             description: "Embedded 360 photo or walkthrough video so prospects see the space before walking in."                                           },
    ],
    animationIdeas: [
      "Stat count-up with heartbeat pulse effect on completion",
      "Hero parallax with dark overlay that lightens on scroll",
      "Progress bar fill on scroll — strength-building analogy",
      "Thumping entrance animation on each section — synced to imagined beat",
      "Trainer card flip to reveal credentials on hover",
    ],
    contentInputIdeas: [
      "Gym interior and equipment photos (wide + detail shots)",
      "Trainer headshots and bio text",
      "Class schedule (Google Sheet or PDF)",
      "Membership pricing tiers and what's included",
      "Transformation photos from members (with written consent)",
      "Before/after videos or testimonials",
      "Any certifications or press mentions",
    ],
    designNotes: "Dark, high-contrast, aggressive energy. Use bold weight typography and powerful photography. The hero should feel like walking into a championship gym. Membership and free-trial CTAs must be above the fold. Accent colors should pop hard against the dark background. high-energy or bold-contractor style packs recommended.",
    recommendedCustomModules: [],
    importantBusinessFields: ["businessName", "city", "phone", "email", "services", "businessDescription"],
    mediaNeeds: ["facility exterior and interior", "equipment in use", "class-in-action shots", "trainer headshots", "transformation photos (consent required)"],
    trustProofNeeds: ["certified trainers", "years in operation", "active member count", "measurable results"],
    ctaStrategy: "Free trial class or free consultation. Low commitment entry point to get people in the door.",
    quoteOrBookingNeeds: "Free trial class booking: name, email, phone, preferred class time and type.",
    menuOrPricingNeeds: true,
    aiPromptNotes: "High-energy, motivational tone. Focus on results, community, and accountability. Use active language. Avoid intimidating language for beginners — inclusive but intense.",
    content: {
      heroHeadlineTemplate: "Train Harder. Live Better. Right Here in {city}.",
      heroSubheadlineTemplate: "{businessName} — where {city} gets stronger, together, every single day.",
      heroCtaText: "Claim Your Free Trial Class",
      heroBadgeTemplate: "Results-Driven · Community-Focused · {city}",
      servicesHeading: "Our Classes & Programs",
      servicesSubheadline: "Something for every fitness level — from first-timers to competitors.",
      defaultServices: [
        { icon: "🏋️", title: "Group Fitness Classes", description: "High-energy group classes for all levels — cardio, strength, and mobility."     },
        { icon: "💪", title: "Personal Training",      description: "1-on-1 sessions with certified coaches, tailored to your specific goals."       },
        { icon: "🧘", title: "Specialty Programs",     description: "Yoga, HIIT, performance training, and more — we have something for everyone."  },
        { icon: "🥗", title: "Nutrition Coaching",     description: "Practical nutrition guidance to fuel your fitness and lock in results."         },
      ],
      statsDefaults: [
        { value: "500+", label: "Active Members"     },
        { value: "4.9★", label: "Member Rating"      },
        { value: "20+",  label: "Classes Per Week"   },
        { value: "100%", label: "Certified Trainers" },
      ],
      whyReasons: [
        { icon: "🏆", title: "Certified Coaches",    description: "Every trainer is certified and experienced. No guessing — just results."                },
        { icon: "👥", title: "Real Community",       description: "Not just a gym — a crew. Members push each other and celebrate every win."             },
        { icon: "📅", title: "Flexible Scheduling",  description: "Morning, midday, evening, and weekend classes. Built around your life."               },
        { icon: "📈", title: "Proven Results",       description: "Our members see real change — in strength, endurance, and confidence."                 },
        { icon: "🔑", title: "All Fitness Levels",   description: "Whether it's day one or year five, we meet you where you are."                       },
        { icon: "💪", title: "Modern Equipment",     description: "Top-of-the-line equipment in a clean, motivating environment."                        },
      ],
      reviewsHeading: "Real Members. Real Results.",
      reviewsDefaults: [
        { name: "Sarah M.", rating: 5, text: "I've tried a lot of gyms and this one is different. The community here is real and the coaches actually know their stuff." },
        { name: "James T.", rating: 5, text: "Down 20 lbs and stronger than I've been in years. The programming works and the coaches hold you accountable." },
        { name: "Linda R.", rating: 5, text: "Intimidating at first but everyone was so welcoming. Went from barely showing up to being here 4 days a week. Best decision I've made." },
      ],
      faqDefaults: [
        { question: "Do I need to be in shape to start?",     answer: "Not at all. We welcome all fitness levels. Our coaches scale every workout to where you are right now."                    },
        { question: "What's included with a membership?",     answer: "Unlimited class access, use of all equipment, and access to our member community. Details vary by membership tier."        },
        { question: "Can I try a class before committing?",   answer: "Yes — your first class is free. No credit card, no commitment. Just show up."                                            },
        { question: "What should I bring to my first class?", answer: "Wear comfortable workout clothes and bring water. We have everything else you need."                                      },
      ],
      finalCtaHeading: "Your First Class is Free",
      finalCtaSubheading: "No commitment. No pressure. Just show up and see what {businessName} is about.",
      finalCtaText: "Claim Free Trial Class",
    },
  },

  // ── 3. Personal Trainer ──────────────────────────────────────────
  {
    id: "personal-trainer",
    industryName: "Personal Trainer",
    aliases: ["personal trainer", "fitness coach", "strength coach", "sports performance", "online coach", "1-on-1 training"],
    recommendedStylePacks: ["bold-contractor", "high-energy", "clean-pro"],
    activeSectionOrder: [
      "HeroAnimated",
      "AnimatedStats",
      "ServicesShowcase",
      "WhyChooseUs",
      "ReviewsCarousel",
      "FAQAccordion",
      "FinalCTA",
      "FooterPremium",
    ],
    plannedSections: [
      { type: "TrainerProfile",     label: "Trainer Profile",              description: "Personal bio, credentials, philosophy, and training journey",        priority: "high"   },
      { type: "ProgramsPackages",   label: "Programs & Packages",          description: "1-on-1, group coaching, and online programs with pricing",           priority: "high"   },
      { type: "BeforeAfterGallery", label: "Client Transformation Gallery",description: "Before/after results with client testimonials (consent required)",  priority: "high"   },
      { type: "BookingCTA",         label: "Free Consultation Booking",    description: "Inline booking for a free intro call or fitness assessment",         priority: "high"   },
    ],
    optionalPremiumSections: ["GalleryMasonry"],
    experimentalConcepts: [
      { id: "CoachingApproachVideo",  concept: "30-Second Coach Intro Video", description: "Short autoplay video of the trainer talking directly to the visitor — the most personal possible introduction."              },
      { id: "ClientResultsWall",      concept: "Client Result Spotlight Wall", description: "Expandable card grid of client transformations — each card shows a stat highlight and short quote."                       },
      { id: "FitnessAssessmentQuiz",  concept: "Free Online Assessment Quiz",  description: "5-question quiz (current fitness, goals, schedule, injuries) → personalized program recommendation + consultation CTA."   },
    ],
    animationIdeas: [
      "Stat counter for clients coached, years experience — fires on scroll into view",
      "Coach photo parallax scroll effect with quote overlay",
      "Testimonial cards that fan in from the side on enter",
    ],
    contentInputIdeas: [
      "Professional trainer headshot (not phone selfie)",
      "Action shots working with clients",
      "Certification and credential photos or text",
      "Client before/after photos (written consent required)",
      "Short personal bio (200–300 words)",
      "Training philosophy statement",
      "List of programs with inclusions and pricing",
    ],
    designNotes: "This is a PERSON, not a corporate gym. The trainer's face, voice, and story should dominate the site. Personable photography beats polished stock art. Focus on the relationship and results. Keep CTAs personal ('Let's talk about your goals') rather than transactional.",
    recommendedCustomModules: [],
    importantBusinessFields: ["businessName", "city", "phone", "email", "services", "businessDescription", "websiteGoals"],
    mediaNeeds: ["trainer headshot (professional)", "action shots training clients", "before/after client photos (consent)", "credentials display"],
    trustProofNeeds: ["certifications (NASM, NSCA, ACE, etc.)", "years coaching", "client results", "specialties"],
    ctaStrategy: "Free discovery call or fitness assessment. Personal, approachable tone — this is a relationship-driven service.",
    quoteOrBookingNeeds: "Free consultation form: name, email, phone, fitness goals, current experience level.",
    menuOrPricingNeeds: true,
    aiPromptNotes: "Personal, authentic, results-focused. This is a person, not a corporation. Highlight the trainer's specific approach. Differentiate from a generic gym membership.",
    content: {
      heroHeadlineTemplate: "Your Strongest Self Starts Here",
      heroSubheadlineTemplate: "{businessName} — personal coaching built around your goals, your schedule, and your life in {city}.",
      heroCtaText: "Book Free Consultation",
      heroBadgeTemplate: "Certified · Results-Driven · {city}",
      servicesHeading: "Programs & Services",
      servicesSubheadline: "Personalized training that fits your goals — not a one-size-fits-all plan.",
      defaultServices: [
        { icon: "🎯", title: "1-on-1 Personal Training", description: "Private sessions tailored 100% to your goals, schedule, and starting point."    },
        { icon: "📱", title: "Online Coaching",           description: "Full coaching remotely — app-based programming, check-ins, and daily support."   },
        { icon: "🥗", title: "Nutrition Coaching",        description: "Practical nutrition guidance built around your lifestyle. No fad diets."         },
        { icon: "📊", title: "Progress Tracking",         description: "Regular assessments and adjustments so you always know you're moving forward."   },
      ],
      statsDefaults: [
        { value: "200+", label: "Clients Coached"    },
        { value: "4.9★", label: "Client Rating"      },
        { value: "8+",   label: "Years Coaching"     },
        { value: "100%", label: "Personalized Plans" },
      ],
      whyReasons: [
        { icon: "🎯", title: "Goal-First Approach",       description: "Every program starts with YOUR goals — not a template. We build a plan that fits your life."        },
        { icon: "📊", title: "Tracked Progress",          description: "Regular check-ins, measurements, and adjustments so you always know you're moving forward."        },
        { icon: "🤝", title: "Real Accountability",       description: "I'm in your corner every step. Text access, weekly check-ins, and someone who genuinely cares."  },
        { icon: "🥗", title: "Nutrition Included",        description: "Training is only half the equation. Practical nutrition coaching — no fad diets."                 },
        { icon: "💡", title: "Education, Not Dependency", description: "I teach you HOW to train so you can succeed long after our work together."                        },
      ],
      reviewsDefaults: [
        { name: "Sarah M.", rating: 5, text: "I hired a trainer because I needed accountability, and I got so much more than that. Down 30 lbs and completely changed how I think about training." },
        { name: "James T.", rating: 5, text: "The personalized programming made all the difference. I'd been stuck for years — within 8 weeks I was past it." },
        { name: "Linda R.", rating: 5, text: "Not just a trainer — a real coach. They check in, they adjust, and they genuinely care about your progress. Completely worth it." },
      ],
      faqDefaults: [
        { question: "Do you offer online coaching or only in-person?",     answer: "Both. Online coaching is fully supported with video check-ins, app-based programming, and daily support."                              },
        { question: "How soon will I see results?",                        answer: "Most clients notice changes in 4–6 weeks. Significant transformation typically happens at 8–12 weeks with consistent effort."           },
        { question: "What makes your coaching different from a gym?",      answer: "A gym membership is equipment access. My coaching is a relationship — a custom plan, regular check-ins, and accountability for results." },
        { question: "What does the free consultation include?",            answer: "We'll discuss your goals, current routine, any limitations, and what success looks like for you. Zero sales pressure."                 },
      ],
      finalCtaHeading: "Ready to Train Differently?",
      finalCtaSubheading: "Book your free 30-minute call with {businessName} and let's build a plan around your goals.",
      finalCtaText: "Book Free Consultation",
    },
  },

  // ── 4. Pressure Washing ──────────────────────────────────────────
  {
    id: "pressure-washing",
    industryName: "Pressure Washing",
    aliases: ["pressure washing", "power washing", "soft washing", "exterior cleaning", "house washing", "driveway cleaning"],
    recommendedStylePacks: ["bold-contractor", "clean-pro", "high-energy"],
    activeSectionOrder: [
      "HeroAnimated",
      "PressureWashRevealSection",
      "AnimatedStats",
      "ServicesShowcase",
      "GalleryMasonry",
      "WhyChooseUs",
      "ReviewsCarousel",
      "FAQAccordion",
      "FinalCTA",
      "FooterPremium",
    ],
    plannedSections: [
      { type: "BeforeAfterGallery", label: "Before & After Gallery", description: "Side-by-side job results with surface type and location labels", priority: "high"   },
      { type: "ServiceAreaMap",     label: "Service Area",           description: "Visual map or list of covered ZIP codes and cities",            priority: "medium" },
    ],
    optionalPremiumSections: ["AnimatedStats"],
    experimentalConcepts: [
      { id: "DragRevealSlider",     concept: "Drag Before/After Reveal",      description: "Interactive drag slider: dirty surface on left, clean surface on right — user drags to reveal. Converts better than any photo."         },
      { id: "QuoteEstimatorWidget", concept: "Instant Quote Estimator",       description: "Form: select surface type + approximate square footage → shows estimated price range. Filters serious leads before the phone call."     },
      { id: "PhotoSubmitQuote",     concept: "Text-a-Photo Quote",            description: "CTA: 'Text us a photo and get a quote in under 2 hours.' No form friction — they text a photo of their driveway, we respond fast."      },
      { id: "JobMapWall",           concept: "Live Job Map (Service Area)",   description: "Map showing recent jobs in the service area with job type pins — proves local presence and coverage."                                   },
    ],
    animationIdeas: [
      "Water spray beam sweep on PressureWashRevealSection entry — already built",
      "Before/after clip-path reveal on scroll — already built",
      "Water droplet particles drifting down on hero section",
      "Stat counter: jobs completed ticks up on scroll",
      "Service card flip to reveal 'before' photo on back",
    ],
    contentInputIdeas: [
      "Before/after photos from recent jobs (driveway, house wash, roof, deck)",
      "Truck or equipment photo with branding",
      "Crew on-the-job action shots",
      "List of cities or ZIP codes in service area",
      "License and insurance certificate numbers (for trust signals)",
      "Any 5-star Google review screenshots",
    ],
    designNotes: "Bold, confident, transformation-focused. Dark backgrounds with accent-colored water element details. Before/after imagery is the #1 converter — center the design around it. The wash reveal animation is a signature moment — don't bury it below the fold. bold-contractor style pack is the default.",
    recommendedCustomModules: ["PressureWashRevealSection", "GalleryMasonry"],
    importantBusinessFields: ["businessName", "city", "serviceArea", "phone", "services"],
    mediaNeeds: ["before/after photos (driveway, house, roof, deck)", "truck/equipment photo", "crew on the job"],
    trustProofNeeds: ["licensed & insured badge", "years in business", "plant/property safe guarantee", "jobs completed count"],
    ctaStrategy: "Same-day quote. Emphasize speed, trust, and the wow factor of a clean property.",
    quoteOrBookingNeeds: "Quick quote form: name, phone, address, surface type, approximate square footage.",
    menuOrPricingNeeds: false,
    aiPromptNotes: "Confident, results-focused tone. Homeowners want trust (won't damage my property) and results (impressive before/after). Direct, action-oriented language.",
    content: {
      heroHeadlineTemplate: "Before & After. Every Single Job.",
      heroSubheadlineTemplate: "{businessName} — professional pressure washing for {area} homes and businesses. Fast quotes. Stunning results.",
      heroCtaText: "Get a Free Quote",
      heroBadgeTemplate: "Serving {area} · Licensed & Insured",
      servicesHeading: "What We Clean",
      servicesSubheadline: "From driveways to roof shingles — no surface is too tough.",
      defaultServices: [
        { icon: "🏠", title: "House & Siding Washing",  description: "Soft wash treatment that removes algae, mildew, and oxidation from any siding type."      },
        { icon: "🚗", title: "Driveway & Concrete",     description: "High-pressure cleaning that lifts years of stains, oil, and grime from concrete and pavers." },
        { icon: "🏗️", title: "Roof Soft Washing",      description: "Eco-safe roof cleaning that removes black streaks without voiding your roofing warranty."    },
        { icon: "🪵", title: "Deck & Fence Cleaning",   description: "Restore wood and composite decks to clean, like-new condition before staining or sealing."   },
      ],
      statsDefaults: [
        { value: "1,200+", label: "Jobs Completed"       },
        { value: "4.9★",   label: "Average Rating"       },
        { value: "5+",     label: "Years Experience"     },
        { value: "0%",     label: "Property Damage Rate" },
      ],
      whyReasons: [
        { icon: "💧", title: "Plant & Property Safe",     description: "Our cleaning solutions are eco-safe and we protect your landscaping before every job."      },
        { icon: "🛡️", title: "Fully Licensed & Insured", description: "We carry full liability coverage on every job. Your property is always protected."           },
        { icon: "📸", title: "Before & After Photos",     description: "Every job is documented. You see the difference before we leave your property."              },
        { icon: "⚡", title: "Same-Day Quotes",           description: "Text us a photo or we come out same day. You'll have a quote before lunch."                 },
        { icon: "🏆", title: "Satisfaction Guaranteed",   description: "Not happy? We come back and make it right. That's our promise, every time."                 },
        { icon: "🌱", title: "Eco-Friendly Solutions",    description: "Biodegradable cleaning agents that are tough on grime and safe for the environment."         },
      ],
      faqDefaults: [
        { question: "Is pressure washing safe for my roof and siding?",     answer: "We use low-pressure soft washing on roofs and delicate surfaces. No damage risk when done correctly — and we always do it correctly." },
        { question: "Will you protect my plants and landscaping?",          answer: "Always. We wet down all landscaping before and after, and use eco-safe agents that won't harm your plants."                          },
        { question: "How long does a typical job take?",                    answer: "A driveway takes 1–2 hours. A full house wash takes 3–4 hours. We give you a time estimate at quoting."                           },
        { question: "Do I need to be home during the service?",             answer: "No — as long as we have water access, we can work while you're away and send before/after photos when done."                       },
      ],
      finalCtaHeading: "Get Your Free Quote Today",
      finalCtaSubheading: "Fast response, honest pricing, and results that speak for themselves. {businessName} has you covered.",
      finalCtaText: "Get My Free Quote",
    },
  },

  // ── 5. Landscaping ───────────────────────────────────────────────
  {
    id: "landscaping",
    industryName: "Landscaping",
    aliases: ["landscaping", "lawn care", "lawn service", "lawn maintenance", "yard care", "outdoor services", "mowing", "lawn & landscaping"],
    recommendedStylePacks: ["clean-pro", "bold-contractor", "premium-glass"],
    activeSectionOrder: [
      "HeroAnimated",
      "AnimatedStats",
      "ServicesShowcase",
      "GalleryMasonry",
      "WhyChooseUs",
      "ReviewsCarousel",
      "FAQAccordion",
      "FinalCTA",
      "FooterPremium",
    ],
    plannedSections: [
      { type: "SeasonalServices",       label: "Seasonal Services",      description: "Spring cleanup, summer mowing, fall prep, winter snow removal",         priority: "high"   },
      { type: "MaintenancePlans",       label: "Maintenance Plans",      description: "Monthly and seasonal maintenance packages with clear scope",            priority: "high"   },
      { type: "LandscapeDesignSection", label: "Landscape Design",       description: "Design consultation process and portfolio of completed projects",       priority: "medium" },
      { type: "BeforeAfterGallery",     label: "Before & After Gallery", description: "Dramatic lawn/landscape transformations",                               priority: "high"   },
    ],
    optionalPremiumSections: ["PressureWashRevealSection"],
    experimentalConcepts: [
      { id: "SeasonalChecklist",             concept: "Seasonal Lawn Care Checklist",   description: "Interactive checklist by season — helps homeowners understand what care their lawn needs and positions the company as the expert." },
      { id: "MaintenancePlanCalculator",     concept: "Maintenance Plan Calculator",    description: "Lot size input → recommended service frequency and estimated monthly cost. Drives plan sales with zero sales call."             },
      { id: "YardAuditPhoto",               concept: "Photo Yard Audit CTA",           description: "'Send us 3 photos of your yard and we'll send a free seasonal plan.' Generates leads through content value."                   },
    ],
    animationIdeas: [
      "Slow parallax grass/garden background in hero",
      "Before/after lawn reveal animation (similar to pressure wash reveal)",
      "Stat count-up: properties maintained, years, show-up rate",
      "Seasonal section with subtle leaf or snow particle effect based on season",
    ],
    contentInputIdeas: [
      "Project photos (before/after lawn transformations)",
      "Seasonal service breakdown (what's included in each)",
      "Service area cities and ZIP codes",
      "Crew/equipment photos",
      "Maintenance plan pricing tiers",
      "Any HOA or commercial client logos",
    ],
    designNotes: "Clean, fresh, outdoorsy. Green accents on light backgrounds. Reliability and consistency are the emotional promise — the design should feel organized, not flashy. clean-pro style pack is the default. Photography should show lush, well-maintained properties in good light.",
    recommendedCustomModules: ["GalleryMasonry"],
    importantBusinessFields: ["businessName", "city", "serviceArea", "phone", "services"],
    mediaNeeds: ["project gallery (before/after)", "seasonal service photos", "crew on-site", "close-ups of finished detail work"],
    trustProofNeeds: ["licensed & insured", "years in business", "properties maintained count", "service area"],
    ctaStrategy: "Free estimate or consultation. Seasonal urgency (spring, fall) works well as a hook.",
    quoteOrBookingNeeds: "Free estimate form: name, phone, address, service type, lot size.",
    menuOrPricingNeeds: true,
    aiPromptNotes: "Professional but approachable. Customers want reliability and consistency long-term. Emphasize seasonal planning and an ongoing, trusted relationship.",
    content: {
      heroHeadlineTemplate: "The Lawn Your Neighbors Will Notice",
      heroSubheadlineTemplate: "{businessName} — reliable lawn care and beautiful landscapes for {area} homeowners.",
      heroCtaText: "Get a Free Estimate",
      heroBadgeTemplate: "Serving {area} · Licensed & Insured",
      servicesHeading: "Our Services",
      servicesSubheadline: "From weekly mowing to full landscape design — we handle it all.",
      defaultServices: [
        { icon: "🌿", title: "Lawn Mowing & Edging", description: "Consistent, professional cuts — edging, trimming, and cleanup included every visit."               },
        { icon: "🌸", title: "Landscape Design",     description: "From concept to completion — plant selection, bed installation, and curb appeal upgrades."       },
        { icon: "🍂", title: "Seasonal Cleanup",     description: "Spring and fall cleanup that prepares your property for each season and protects your investment." },
        { icon: "💧", title: "Irrigation Services",  description: "Sprinkler system installation, maintenance, and seasonal activation and winterization."           },
      ],
      statsDefaults: [
        { value: "300+", label: "Properties Maintained" },
        { value: "4.9★", label: "Customer Rating"       },
        { value: "7+",   label: "Years in Business"     },
        { value: "100%", label: "Show-Up Rate"          },
      ],
      whyReasons: [
        { icon: "📅", title: "Consistent & Reliable",   description: "We show up every scheduled visit, every time. No missed appointments, no excuses."         },
        { icon: "🌿", title: "Seasonal Expertise",      description: "We know what {city} lawns need — spring cleanup to winterization, we plan ahead."          },
        { icon: "🛡️", title: "Licensed & Insured",     description: "Fully licensed and insured. Your property is protected on every visit."                    },
        { icon: "🔧", title: "Professional Equipment",  description: "Commercial-grade equipment ensures a clean, professional finish every time."                },
        { icon: "🤝", title: "Long-Term Relationships", description: "Most of our clients have been with us for years. We know your property like our own."      },
      ],
      faqDefaults: [
        { question: "Do you offer regular maintenance contracts?",    answer: "Yes — weekly, bi-weekly, and monthly plans. Most clients save with a seasonal contract vs. one-time visits." },
        { question: "What's included in a basic maintenance visit?", answer: "Mowing, edging, trimming, and blowing. Seasonal add-ons like aerating and fertilizing are available."        },
        { question: "Do I need to be home during service?",          answer: "No. Most clients are at work when we come. We leave a service note and keep the gate requirements on file."  },
        { question: "What areas do you serve?",                      answer: "We serve {area} and surrounding areas. Fill out our form or call to confirm your address."                   },
      ],
      finalCtaHeading: "Ready for a Lawn You're Proud Of?",
      finalCtaSubheading: "Get a free estimate from {businessName} and see why {city} trusts us with their most important outdoor space.",
      finalCtaText: "Get Free Estimate",
    },
  },

  // ── 6. Barber / Salon ────────────────────────────────────────────
  {
    id: "barber-salon",
    industryName: "Barber / Salon",
    aliases: ["barber", "barbershop", "hair salon", "salon", "beauty salon", "hair stylist", "hairdresser", "hair studio", "nail salon"],
    recommendedStylePacks: ["luxury-dark", "clean-pro", "premium-glass"],
    activeSectionOrder: [
      "HeroAnimated",
      "AnimatedStats",
      "ServicesShowcase",
      "GalleryMasonry",
      "ReviewsCarousel",
      "FAQAccordion",
      "FinalCTA",
      "FooterPremium",
    ],
    plannedSections: [
      { type: "StaffProfiles", label: "Meet the Stylists",       description: "Individual profiles with specialties, photos, and individual booking links",  priority: "high"   },
      { type: "BookingCTA",    label: "Online Booking Widget",   description: "Inline appointment booking — calendar integration or waitlist flow",           priority: "high"   },
      { type: "ServiceMenu",   label: "Service Menu & Pricing",  description: "Full menu with descriptions and prices organized by category",                 priority: "high"   },
    ],
    optionalPremiumSections: ["WhyChooseUs"],
    experimentalConcepts: [
      { id: "StyleLookbook",    concept: "Digital Style Lookbook",      description: "Scrollable gallery of cuts and styles done at this shop — organized by type (fades, beards, colors). Drives bookings with social proof."  },
      { id: "BookingMinimizer", concept: "1-Click Appointment Request", description: "Single-field phone number entry on the hero → triggers a text confirmation. Maximum conversion, minimum friction."                       },
      { id: "StylistMatchQuiz", concept: "Find Your Stylist Quiz",      description: "3-question quiz (hair type, style preference, vibe) → recommends the right stylist + direct booking link. Personalizes the funnel."      },
    ],
    animationIdeas: [
      "Portfolio photo grid with smooth hover zoom on each cut",
      "Gold shimmer sweep on the booking CTA button",
      "Stylist cards with scissors icon that animate on hover",
      "Smooth dark-mode gradient hero that breathes (CSS animation)",
    ],
    contentInputIdeas: [
      "Shop interior photo (wide shot of chairs/mirrors)",
      "Individual stylist headshots + short bio per stylist",
      "Before/after cut or color photos",
      "Full service menu with prices",
      "Hours of operation",
      "Walk-in policy statement",
      "Any awards, press, or 'Best of' recognitions",
    ],
    designNotes: "For barbershops: masculine, clean, dark luxury. Think Italian barber — dark woods, chrome, deliberate negative space. For salons: warmer, lifestyle-forward, aspirational. The luxury-dark pack is ideal for most. Photography should feel editorial, not casual. The portfolio/gallery is the most important trust signal.",
    recommendedCustomModules: ["GalleryMasonry"],
    importantBusinessFields: ["businessName", "city", "phone", "email", "services", "businessDescription"],
    mediaNeeds: ["shop/salon interior (wide shot)", "stylist headshots", "before/after hair photos", "product and tool close-ups", "ambiance shots"],
    trustProofNeeds: ["years in business", "licensed stylists", "client portfolio", "appointment availability"],
    ctaStrategy: "Book an appointment. Reduce friction — clear, prominent booking CTA above the fold.",
    quoteOrBookingNeeds: "Online booking: service type, preferred stylist, preferred date and time.",
    menuOrPricingNeeds: true,
    aiPromptNotes: "Confident, style-forward tone. For barbershops, clean and masculine. For salons, warmer and lifestyle-oriented. Emphasize the experience and environment, not just the service.",
    content: {
      heroHeadlineTemplate: "Look Sharp. Feel Confident.",
      heroSubheadlineTemplate: "{businessName} — expert cuts, clean fades, and a {city} shop worth coming back to.",
      heroCtaText: "Book an Appointment",
      heroBadgeTemplate: "Walk-ins Welcome · {city}",
      servicesHeading: "Our Services",
      servicesSubheadline: "Every cut is a commitment to quality. Here's what we do best.",
      defaultServices: [
        { icon: "✂️", title: "Haircuts & Styling", description: "Precision cuts and styling for every hair type, length, and lifestyle."         },
        { icon: "🪒", title: "Beard Shaping",      description: "Full beard trims, lineup, and hot towel shaves. Clean lines, every time."      },
        { icon: "🎨", title: "Color Services",      description: "Highlights, balayage, full color, and toning — done right the first time."    },
        { icon: "💆", title: "Scalp Treatments",    description: "Conditioning and scalp treatments that promote healthy hair from the root up." },
      ],
      statsDefaults: [
        { value: "2,000+", label: "Happy Clients"    },
        { value: "4.9★",   label: "Average Rating"   },
        { value: "10+",    label: "Years in {city}"  },
        { value: "100%",   label: "Licensed Stylists"},
      ],
      whyReasons: [
        { icon: "✂️", title: "Skilled & Experienced",  description: "Our stylists have years of experience and stay current on every trend and technique."       },
        { icon: "🕐", title: "On Time, Every Time",    description: "We respect your schedule. Book ahead and we'll be ready when you walk in."                  },
        { icon: "🌟", title: "Clean & Comfortable",    description: "A shop you actually enjoy being in — clean, modern, and welcoming for everyone."           },
        { icon: "💬", title: "You're Always Heard",    description: "We listen first. Every cut is a conversation — we do what you want, not what we assume."   },
        { icon: "🔄", title: "We Remember You",        description: "Walk in twice and we know your cut, your preferences, and your name."                      },
      ],
      reviewsDefaults: [
        { name: "Sarah M.", rating: 5, text: "Best haircut I've had in years. They actually listened to what I wanted and delivered exactly that. I won't go anywhere else now." },
        { name: "James T.", rating: 5, text: "Clean shop, great vibe, and my stylist knew exactly what to do. Walked in feeling rough and walked out feeling sharp." },
        { name: "Linda R.", rating: 5, text: "I've been searching for a great salon for a long time. Finally found it. Booked my next appointment before I even left." },
      ],
      faqDefaults: [
        { question: "Do you take walk-ins?",             answer: "Yes — walk-ins are always welcome, but booking ahead guarantees your preferred time and stylist."       },
        { question: "How do I book an appointment?",     answer: "Call us, book online, or walk in. We'll get you sorted quickly."                                      },
        { question: "What's your cancellation policy?",  answer: "We ask for 24 hours notice for cancellations. Life happens — just let us know ahead of time."        },
        { question: "Do you do color or just cuts?",     answer: "It depends on the stylists available. Contact us to confirm the full service menu for your location." },
      ],
      finalCtaHeading: "Your Next Great Cut is One Click Away",
      finalCtaSubheading: "Book with {businessName} and walk out looking exactly how you want.",
      finalCtaText: "Book My Appointment",
    },
  },

  // ── 7. Restaurant / Cafe ─────────────────────────────────────────
  {
    id: "restaurant-cafe",
    industryName: "Restaurant / Cafe",
    aliases: ["restaurant", "cafe", "coffee shop", "diner", "bistro", "food truck", "pizzeria", "bakery", "catering", "eatery"],
    recommendedStylePacks: ["luxury-dark", "clean-pro", "premium-glass"],
    activeSectionOrder: [
      "HeroAnimated",
      "ServicesShowcase",
      "GalleryMasonry",
      "ReviewsCarousel",
      "FooterPremium",
    ],
    plannedSections: [
      { type: "MenuShowcase",   label: "Full Menu",                   description: "Visual menu by category with photos, descriptions, and prices",             priority: "high"   },
      { type: "FeaturedItems",  label: "Featured Dishes",             description: "Spotlight on signature dishes with full-bleed photography",                 priority: "high"   },
      { type: "HoursLocation",  label: "Hours & Location",            description: "Hours of operation with holiday exceptions and embedded map",               priority: "high"   },
      { type: "OnlineOrdering", label: "Order Online / Reserve",      description: "Integration with Toast, Square, OpenTable, or Yelp reservation link",      priority: "high"   },
      { type: "Specials",       label: "Daily Specials / Happy Hour", description: "Rotating specials, happy hour deals, and seasonal items",                   priority: "medium" },
      { type: "CateringSection",label: "Catering & Private Events",   description: "Catering packages and private dining inquiry form",                         priority: "medium" },
    ],
    optionalPremiumSections: ["FAQAccordion", "WhyChooseUs", "FinalCTA", "AnimatedStats"],
    experimentalConcepts: [
      { id: "DailySpecialBanner",concept: "Today's Special Live Banner",   description: "Editable banner the owner updates daily — 'Today's Special: [dish] $[price]' — keeps the site feeling alive and drives repeat visits." },
      { id: "MenuFlipbook",      concept: "Swipeable Menu Flipbook",       description: "Mobile-native swipe-through of menu categories — feels like holding a real menu."                                                    },
      { id: "OnlineOrderCTA",    concept: "1-Click Online Order Button",   description: "Sticky 'Order Now' button that links to Toast/Square/DoorDash. Always visible on mobile — biggest conversion win for restaurants."  },
    ],
    animationIdeas: [
      "Food photography parallax scroll with warm overlay tint",
      "Menu category tabs with smooth slide transition",
      "Review cards that softly fade in on scroll",
      "Hero background video loop (kitchen prep, steam, plating) — future media option",
    ],
    contentInputIdeas: [
      "Food photography (must be high quality — this is the #1 converter)",
      "Full menu with descriptions and prices",
      "Interior and exterior photos",
      "Chef or team photos",
      "Hours of operation",
      "Reservation or ordering link (OpenTable, Toast, etc.)",
      "Any press mentions or awards",
      "Catering menu PDF",
    ],
    designNotes: "Food photography is everything. The design exists to frame and feature the food. Dark, moody backgrounds (luxury-dark) work well for upscale dining. Lighter, fresher palettes (clean-pro) work for cafes. Never show empty plates or stock photography — real food photos are non-negotiable for this industry.",
    recommendedCustomModules: ["GalleryMasonry"],
    importantBusinessFields: ["businessName", "city", "phone", "email", "services", "businessDescription"],
    mediaNeeds: ["food photography (high quality)", "interior ambiance shots", "exterior and signage", "chef or team photos", "plating close-ups"],
    trustProofNeeds: ["years open", "Google/Yelp star rating", "press mentions", "health inspection grade"],
    ctaStrategy: "View the menu or make a reservation. Food photos and reviews are primary conversion drivers.",
    quoteOrBookingNeeds: "Reservation link or online ordering integration. Separate catering inquiry form.",
    menuOrPricingNeeds: true,
    aiPromptNotes: "Warm, sensory, inviting tone. Make visitors feel hungry and excited to come in. Use descriptive food language. For cafes, lean into atmosphere and ritual.",
    content: {
      heroHeadlineTemplate: "Food Worth Coming Back For",
      heroSubheadlineTemplate: "{businessName} — where every meal is made with care and every guest feels at home in {city}.",
      heroCtaText: "View Our Menu",
      heroBadgeTemplate: "Dine In & Takeout · {city}",
      servicesHeading: "What We Serve",
      servicesSubheadline: "Made fresh, made with love — here's a taste of what's waiting for you.",
      defaultServices: [
        { icon: "🍽️", title: "Dine-In Experience", description: "A welcoming space where you can slow down, enjoy great food, and feel at home."          },
        { icon: "📦", title: "Takeout & Delivery",  description: "Order online or call — we'll have it ready fresh for pickup or delivery."                },
        { icon: "🎉", title: "Private Events",      description: "We host private dinners, corporate lunches, birthday celebrations, and more."            },
        { icon: "🥗", title: "Catering",            description: "Full-service catering for your event — menus customized to your group and occasion."     },
      ],
      statsDefaults: [
        { value: "500+",  label: "Happy Diners Weekly"  },
        { value: "4.8★",  label: "Google Rating"        },
        { value: "Fresh", label: "Daily Ingredients"    },
        { value: "10+",   label: "Years Serving {city}" },
      ],
      whyReasons: [
        { icon: "🍽️", title: "Made Fresh Daily",     description: "We prep from scratch every day. No frozen shortcuts, ever."                            },
        { icon: "🌿", title: "Quality Ingredients",  description: "We source locally when possible and choose quality over convenience."                   },
        { icon: "🏡", title: "Welcoming Atmosphere", description: "A place where you feel at home — whether it's your first visit or your hundredth."     },
        { icon: "👨‍🍳", title: "Passionate Kitchen",  description: "Our team loves what they make. That passion ends up on every plate."                   },
        { icon: "🎉", title: "Events & Catering",    description: "We handle your special occasions — corporate lunches, birthday dinners, and more."     },
      ],
      reviewsDefaults: [
        { name: "Sarah M.", rating: 5, text: "The food was incredible and the atmosphere made it even better. One of our favorite spots in town — we keep coming back." },
        { name: "James T.", rating: 5, text: "Fresh, flavorful, and the service was warm and attentive. Exactly what a great meal out should feel like." },
        { name: "Linda R.", rating: 5, text: "Brought family visiting from out of town and everyone raved about it. Portions are generous and everything tasted homemade." },
      ],
      faqDefaults: [
        { question: "Do you take reservations?",                answer: "Yes — call us or book online. Walk-ins are welcome based on availability."                                     },
        { question: "Do you offer takeout or delivery?",        answer: "Yes to both. Order online or call us directly."                                                               },
        { question: "Do you accommodate dietary restrictions?", answer: "We do our best. Let your server know about any allergies when you order — our kitchen takes it seriously."    },
        { question: "Can you cater my event?",                  answer: "Absolutely. We do corporate lunches, private parties, and large group events. Contact us to discuss."         },
      ],
      finalCtaHeading: "Come In. Sit Down. Eat Well.",
      finalCtaSubheading: "A great meal is waiting at {businessName}. Make a reservation or order online today.",
      finalCtaText: "View Menu & Order",
    },
  },

  // ── 8. Roofing ───────────────────────────────────────────────────
  {
    id: "roofing",
    industryName: "Roofing",
    aliases: ["roofing", "roofer", "roof repair", "roof replacement", "storm damage", "gutters", "siding contractor"],
    recommendedStylePacks: ["bold-contractor", "clean-pro", "high-energy"],
    activeSectionOrder: [
      "HeroAnimated",
      "AnimatedStats",
      "ServicesShowcase",
      "WhyChooseUs",
      "GalleryMasonry",
      "ReviewsCarousel",
      "FAQAccordion",
      "FinalCTA",
      "FooterPremium",
    ],
    plannedSections: [
      { type: "EmergencyCTA",         label: "Emergency Storm Damage CTA",  description: "Prominent emergency contact with storm documentation guidance",      priority: "high"   },
      { type: "InsuranceClaimSection",label: "Insurance Claim Assistance",  description: "How we work with your carrier — step-by-step process",              priority: "high"   },
      { type: "WarrantySection",      label: "Warranty & Materials",        description: "Manufacturer warranties, workmanship guarantees, material options",  priority: "medium" },
      { type: "BeforeAfterGallery",   label: "Project Gallery",             description: "Before/after roof jobs with type and scope labels",                 priority: "high"   },
    ],
    optionalPremiumSections: [],
    experimentalConcepts: [
      { id: "StormDamageChecklistCTA", concept: "Storm Damage Self-Check Guide",   description: "Downloadable or on-page checklist: 'Signs Your Roof Needs Inspection After a Storm.' Drives organic search traffic and inbound calls." },
      { id: "InsuranceProcessGuide",   concept: "Interactive Insurance Guide",    description: "Step-by-step visual guide of the claims process with {businessName} handling each step. Reduces customer anxiety and positions you as expert." },
      { id: "MaterialSelector",        concept: "Roofing Material Comparison",    description: "Interactive comparison: asphalt vs. metal vs. tile. Shows lifespan, cost range, pros/cons. Helps customer feel informed before calling."   },
    ],
    animationIdeas: [
      "Before/after project gallery reveal on scroll",
      "Stat count-up for roofs completed, years in business",
      "Emergency CTA with subtle pulse animation to draw the eye",
      "Service card with material swatch flip on hover (shingle type preview)",
    ],
    contentInputIdeas: [
      "Completed roofing project photos (multiple angles)",
      "Storm damage documentation photos",
      "Crew on-roof action shots",
      "Material sample photos (shingle types, metal profiles)",
      "Manufacturer certification proof",
      "Insurance carrier logos you work with",
      "Any BBB or contractor association badges",
    ],
    designNotes: "Authoritative and calm — homeowners are nervous when it comes to roofing. The design should feel solid and trustworthy, not salesy. Bold text with dark backgrounds works well. The #1 priority is conveying 'we know what we're doing and we'll protect you.' bold-contractor style pack recommended.",
    recommendedCustomModules: ["GalleryMasonry"],
    importantBusinessFields: ["businessName", "city", "serviceArea", "phone", "services"],
    mediaNeeds: ["completed roofing projects", "storm damage documentation photos", "crew on-roof shots", "material samples", "before/after comparisons"],
    trustProofNeeds: ["licensed & insured", "manufacturer certifications", "BBB accreditation", "years in business", "insurance claim track record"],
    ctaStrategy: "Emergency storm inspection CTA is highest priority. Free inspection offer for non-emergency jobs.",
    quoteOrBookingNeeds: "Free inspection request: name, phone, address, issue type (storm damage, leak, replacement, new build).",
    menuOrPricingNeeds: false,
    aiPromptNotes: "Authoritative, calm, trustworthy. Homeowners are nervous — roofing is expensive and high-stakes. Emphasize expertise, licensing, warranties, and insurance experience. Calm professional language.",
    content: {
      heroHeadlineTemplate: "Protect What's Above You",
      heroSubheadlineTemplate: "{businessName} — trusted roofing repair, replacement, and storm damage claims for {area} homes and businesses.",
      heroCtaText: "Schedule Free Inspection",
      heroBadgeTemplate: "Licensed & Insured · Serving {area}",
      servicesHeading: "Our Roofing Services",
      servicesSubheadline: "From emergency repairs to full replacements — we protect what's overhead.",
      defaultServices: [
        { icon: "🏗️", title: "Roof Replacement",   description: "Full tear-off and replacement with manufacturer-certified materials and workmanship warranty." },
        { icon: "🔧", title: "Roof Repair",         description: "Leak repairs, flashing replacement, and targeted fixes — done right the first time."          },
        { icon: "⛈️", title: "Storm Damage Claims", description: "We work directly with your insurance adjuster and guide you through the full claim process."   },
        { icon: "🔍", title: "Free Inspections",    description: "Comprehensive roof inspection with photos and written report — no obligation, ever."           },
      ],
      statsDefaults: [
        { value: "800+", label: "Roofs Completed"    },
        { value: "4.9★", label: "Homeowner Rating"   },
        { value: "15+",  label: "Years in Business"  },
        { value: "100%", label: "Licensed & Insured" },
      ],
      whyReasons: [
        { icon: "🛡️", title: "Licensed & Fully Insured",    description: "We carry full liability and workers' comp. Your home is protected every step of the way."        },
        { icon: "📋", title: "Insurance Claim Experience",   description: "We've worked with every major carrier. We guide you from inspection to payment."                  },
        { icon: "🏆", title: "Manufacturer Certified",       description: "Certified installer for top roofing brands — warranty backed by us and the manufacturer."        },
        { icon: "📸", title: "Documented Every Step",        description: "Full photo documentation before, during, and after. You see exactly what was done."              },
        { icon: "⚡", title: "Emergency Response",            description: "Storm damage? We respond fast — tarping and emergency repairs to protect your home now."        },
        { icon: "💬", title: "No Pressure, No Surprises",    description: "Free inspection, honest assessment, written estimate. We earn your trust before you spend a dime."},
      ],
      faqDefaults: [
        { question: "Do you help with insurance claims for storm damage?", answer: "Yes — we have deep experience with storm damage claims. We'll document the damage, work with your adjuster, and guide you through the process." },
        { question: "How long does a roof replacement take?",             answer: "Most residential replacements are completed in 1–2 days. We'll give you a specific timeline after assessing your roof."                        },
        { question: "Do I need to be home during the replacement?",       answer: "No, but someone should be available by phone. We'll walk you through before and after."                                                       },
        { question: "What roofing materials do you work with?",           answer: "Asphalt shingles, metal roofing, tile, and flat roofing systems. We'll recommend the best option for your home and budget."                  },
      ],
      finalCtaHeading: "Protect Your Home. Start With a Free Inspection.",
      finalCtaSubheading: "Storm damage or just overdue for a checkup? {businessName} gives you the facts — no sales pressure.",
      finalCtaText: "Schedule Free Inspection",
    },
  },

  // ── 9. Painting ──────────────────────────────────────────────────
  {
    id: "painting",
    industryName: "Painting",
    aliases: ["painting", "house painting", "interior painting", "exterior painting", "painter", "commercial painting", "cabinet painting"],
    recommendedStylePacks: ["clean-pro", "premium-glass", "bold-contractor"],
    activeSectionOrder: [
      "HeroAnimated",
      "AnimatedStats",
      "ServicesShowcase",
      "GalleryMasonry",
      "WhyChooseUs",
      "ReviewsCarousel",
      "FAQAccordion",
      "FinalCTA",
      "FooterPremium",
    ],
    plannedSections: [
      { type: "BeforeAfterGallery", label: "Before & After Gallery", description: "Room and exterior transformations with color names and finish types", priority: "high"   },
      { type: "ColorConsultation",  label: "Color Consultation",     description: "Free color consultation offer with sample bring-to-home process",   priority: "medium" },
    ],
    optionalPremiumSections: ["PressureWashRevealSection"],
    experimentalConcepts: [
      { id: "ColorPreviewTool",     concept: "Room Color Preview",           description: "Upload a photo of your room → apply a paint color from a preset palette → see a rough preview. High novelty, strong conversion."  },
      { id: "ColorSwatchRequest",   concept: "Free Sample Swatch Request",   description: "Pick 3 colors from a digital swatch board → request free physical samples mailed or brought in person. Generates warm leads."     },
      { id: "ProjectQuizEstimator", concept: "Painting Project Estimator",   description: "Room type + approximate square footage → estimated cost range + timeline. Filters and qualifies leads before the phone call."     },
    ],
    animationIdeas: [
      "Color brush stroke wipe reveal on section entry — hero headline appears as a brushstroke sweeps across",
      "Before/after room transformation reveal (clip-path animation, similar to wash reveal)",
      "Paint swatch cards that slide in with staggered delay",
      "Color palette dots that pulse on hover",
    ],
    contentInputIdeas: [
      "Finished project photos (interior rooms — multiple angles)",
      "Exterior paint jobs (before/after strongly preferred)",
      "Cabinet refinishing close-up photos",
      "Crew prepping and painting action shots",
      "List of paint brands used (Sherwin-Williams, Benjamin Moore, etc.)",
      "Color consultation process description",
    ],
    designNotes: "Clean, fresh, transformation-forward. Light or white backgrounds to let project photography breathe. Emphasize the emotional transformation — 'your space will feel like new.' Accent pops of color reference the painting craft. The before/after gallery is the #1 driver — make it prominent.",
    recommendedCustomModules: ["GalleryMasonry"],
    importantBusinessFields: ["businessName", "city", "serviceArea", "phone", "services"],
    mediaNeeds: ["finished project photos (interior + exterior)", "before/after rooms", "trim and detail close-ups", "crew in action"],
    trustProofNeeds: ["licensed & insured", "years painting", "projects completed", "satisfied homeowners"],
    ctaStrategy: "Free estimate. Interior customers want color guidance; exterior customers want durability and curb appeal.",
    quoteOrBookingNeeds: "Free estimate: interior/exterior, approximate square footage, target timeline.",
    menuOrPricingNeeds: false,
    aiPromptNotes: "Clean, fresh, transformation-focused tone. Interior painting is emotional — it changes how a space FEELS. Exterior is about curb appeal and home value. Use visual, color-forward language.",
    content: {
      heroHeadlineTemplate: "Fresh Paint. Fresh Start.",
      heroSubheadlineTemplate: "{businessName} — professional interior and exterior painting for {area} homes and businesses.",
      heroCtaText: "Get a Free Estimate",
      heroBadgeTemplate: "Licensed Painters · Serving {area}",
      servicesHeading: "Our Painting Services",
      servicesSubheadline: "Interior, exterior, commercial, cabinets — we handle it all with precision.",
      defaultServices: [
        { icon: "🏠", title: "Interior Painting",   description: "Walls, ceilings, trim, and cabinets — flawless finish with zero mess left behind."           },
        { icon: "🎨", title: "Exterior Painting",   description: "Weather-resistant paint and expert prep that protects your home and boosts curb appeal."      },
        { icon: "🪵", title: "Cabinet Refinishing", description: "Transform dated cabinets with a professional spray finish — fraction of the cost to replace." },
        { icon: "🏢", title: "Commercial Painting", description: "Interior and exterior for offices, storefronts, and commercial properties of any size."       },
      ],
      statsDefaults: [
        { value: "600+", label: "Projects Completed"       },
        { value: "4.9★", label: "Homeowner Rating"         },
        { value: "10+",  label: "Years Painting"           },
        { value: "100%", label: "Satisfaction Guaranteed"  },
      ],
      whyReasons: [
        { icon: "🎨", title: "Clean & Precise Work",  description: "We tape, protect, and prep everything before we open a can. No cutting corners, ever."  },
        { icon: "🛡️", title: "Licensed & Insured",   description: "Full liability coverage on every job. We protect your home as if it were our own."        },
        { icon: "🌈", title: "Color Expertise",       description: "Not sure what color? We help you pick the right palette for your space and lighting."     },
        { icon: "🧹", title: "Spotless Cleanup",      description: "We leave every job site spotless. You won't find a paint splatter we didn't cover."      },
        { icon: "⏱️", title: "On Time & On Budget",   description: "Written estimate, and we stick to it. No surprise add-ons when the job is done."         },
      ],
      faqDefaults: [
        { question: "How do I prepare my home for interior painting?", answer: "We handle all prep — patching, sanding, taping, and protecting floors and furniture. Just clear personal items from the room." },
        { question: "How long does interior painting take?",           answer: "A single room typically takes 1 day. Whole-home interiors vary — we'll give you a clear timeline in your estimate."         },
        { question: "What brands of paint do you use?",                answer: "We use premium paints like Sherwin-Williams and Benjamin Moore as standard. We'll discuss the best option for your project." },
        { question: "Can you help me choose colors?",                  answer: "Yes — we offer color consultations and can bring samples to your home so you can see how colors look in your actual space."  },
      ],
      finalCtaHeading: "Time for a Fresh Look?",
      finalCtaSubheading: "Get a free, no-pressure estimate from {businessName}. We'll scope the job and give you an honest price.",
      finalCtaText: "Get My Free Estimate",
    },
  },

  // ── 10. HVAC / Plumbing ──────────────────────────────────────────
  {
    id: "hvac-plumbing",
    industryName: "HVAC / Plumbing",
    aliases: ["hvac", "plumbing", "heating", "cooling", "air conditioning", "furnace", "heat pump", "water heater", "drain", "sewer", "mechanical"],
    recommendedStylePacks: ["bold-contractor", "clean-pro", "high-energy"],
    activeSectionOrder: [
      "HeroAnimated",
      "AnimatedStats",
      "ServicesShowcase",
      "WhyChooseUs",
      "ReviewsCarousel",
      "FAQAccordion",
      "FinalCTA",
      "FooterPremium",
    ],
    plannedSections: [
      { type: "EmergencyCTA",         label: "24/7 Emergency Service CTA",  description: "Always-visible emergency call button with after-hours availability",     priority: "high"   },
      { type: "MaintenancePlans",     label: "Maintenance Plans",            description: "Annual HVAC tune-up and plumbing inspection packages",                   priority: "high"   },
      { type: "FinancingPlaceholder", label: "Financing Options",            description: "Placeholder for Synchrony, GreenSky, or similar — future integration",   priority: "medium" },
    ],
    optionalPremiumSections: ["GalleryMasonry"],
    experimentalConcepts: [
      { id: "EmergencyCallBar",        concept: "Sticky Emergency Call Bar",        description: "Always-visible bar at the top of the site with emergency phone number and 'Available Now' indicator. Converts stress-callers instantly."   },
      { id: "MaintenancePlanFinder",   concept: "Maintenance Plan Finder Quiz",     description: "System type + age + last service date → recommended maintenance plan + pricing. Drives plan sign-ups without a phone call."              },
      { id: "SeasonalReminderSignup",  concept: "Season Tune-Up Reminder Signup",   description: "Email capture: 'Remind me when to schedule my spring/fall tune-up.' Builds a list and drives repeat business seasonally."               },
    ],
    animationIdeas: [
      "Emergency call CTA with a subtle pulse ring that draws the eye",
      "Service card hover state with equipment icon animation",
      "Stat count-up for jobs, years licensed, response time",
      "Dark hero with heat wave shimmer or cool blue water ripple on entry",
    ],
    contentInputIdeas: [
      "Technician/team photos on the job",
      "Branded truck or van photo",
      "Equipment or system photos (furnace, AC unit, water heater)",
      "List of brands/systems you service",
      "License and certification numbers",
      "Response time guarantees or guarantees text",
      "Maintenance plan pricing and inclusions",
    ],
    designNotes: "Professional, calm, authoritative. The customer is often stressed — a broken furnace in January or a leaking pipe is an emergency. The design should immediately communicate: 'you called the right people.' bold-contractor for trust and urgency, or clean-pro for a more approachable service company feel. Emergency phone number should never be more than one scroll away.",
    recommendedCustomModules: [],
    importantBusinessFields: ["businessName", "city", "serviceArea", "phone", "services"],
    mediaNeeds: ["technician/team photos", "branded truck or van", "job site photos", "equipment examples"],
    trustProofNeeds: ["licensed & bonded", "24/7 emergency availability", "years in business", "jobs completed", "manufacturer certifications"],
    ctaStrategy: "Emergency call CTA above the fold — many visitors are in a crisis. Also offer free estimates for non-urgent work.",
    quoteOrBookingNeeds: "Service call scheduling: issue type, urgency level, address, preferred time.",
    menuOrPricingNeeds: false,
    aiPromptNotes: "Calm, authoritative, reliable tone. Customers are often stressed — they need to feel in good hands immediately. Lead with availability and trustworthiness. Avoid jargon.",
    content: {
      heroHeadlineTemplate: "Fast Service. Licensed Techs. No Surprises.",
      heroSubheadlineTemplate: "{businessName} — serving {area} homeowners and businesses for heating, cooling, and plumbing needs.",
      heroCtaText: "Call for Service Now",
      heroBadgeTemplate: "Licensed · 24/7 Emergency · {city}",
      servicesHeading: "Our Services",
      servicesSubheadline: "From emergency repairs to routine maintenance — we keep your home running.",
      defaultServices: [
        { icon: "🌡️", title: "Heating & Furnace", description: "Furnace repair, replacement, and annual tune-ups — before the cold season hits."         },
        { icon: "❄️", title: "Air Conditioning",   description: "AC repair, installation, and maintenance for every system type and home size."           },
        { icon: "🔧", title: "Plumbing Repairs",   description: "Leaks, clogs, water heaters, and full repiping — done right and on budget."             },
        { icon: "🗓️", title: "Maintenance Plans",  description: "Annual service agreements that prevent the emergency before it ever happens."           },
      ],
      statsDefaults: [
        { value: "1,000+", label: "Service Calls Completed" },
        { value: "4.9★",   label: "Customer Rating"         },
        { value: "24/7",   label: "Emergency Available"     },
        { value: "15+",    label: "Years Licensed"          },
      ],
      whyReasons: [
        { icon: "🚨", title: "Emergency Response",      description: "We pick up the phone. Day or night, we respond fast to urgent situations."            },
        { icon: "🔑", title: "Licensed & Bonded",       description: "Fully licensed, bonded, and insured. Your home and family are protected."             },
        { icon: "📋", title: "Upfront Pricing",         description: "We diagnose first, quote before we start. No surprises on your invoice."             },
        { icon: "🛠️", title: "Experienced Technicians", description: "Trained on the latest equipment and code. We fix it right the first time."           },
        { icon: "🗓️", title: "Maintenance Plans",       description: "Prevent the emergency before it happens. Ask about our annual service programs."     },
        { icon: "⭐", title: "5-Star Track Record",     description: "Hundreds of satisfied homeowners in {area} trust us year after year."                 },
      ],
      faqDefaults: [
        { question: "Do you offer 24/7 emergency service?",  answer: "Yes — we have technicians available around the clock for genuine emergencies. Call us any time."                                               },
        { question: "Do you provide free estimates?",        answer: "Free estimates for non-emergency replacements and installs. Service/repair calls have a diagnostic fee waived if you proceed."               },
        { question: "How quickly can you respond?",          answer: "For emergencies, we target same-day response. Non-urgent service is typically within 24–48 hours."                                           },
        { question: "Are your technicians licensed?",        answer: "Yes — all technicians are fully licensed and regularly trained on the latest systems and code requirements."                                  },
      ],
      finalCtaHeading: "Need Service? We're Ready.",
      finalCtaSubheading: "{businessName} — fast, licensed, and available when you need us most.",
      finalCtaText: "Schedule Service Now",
    },
  },

  // ── 11. Contractor / Handyman (fallback) ─────────────────────────
  {
    id: "contractor-handyman",
    industryName: "Contractor / Handyman",
    aliases: [
      "contractor", "handyman", "general contractor", "remodeling", "renovation",
      "home repair", "carpenter", "carpentry", "electrician", "electrical",
      "tile", "flooring", "drywall", "concrete", "paving", "fence",
      "cleaning services", "window cleaning", "moving", "junk removal", "other",
    ],
    recommendedStylePacks: ["bold-contractor", "clean-pro", "high-energy"],
    activeSectionOrder: [
      "HeroAnimated",
      "AnimatedStats",
      "ServicesShowcase",
      "GalleryMasonry",
      "WhyChooseUs",
      "ReviewsCarousel",
      "FAQAccordion",
      "FinalCTA",
      "FooterPremium",
    ],
    plannedSections: [
      { type: "ProcessSection", label: "Our Process",  description: "Step-by-step how we handle a job — estimate to cleanup",        priority: "medium" },
      { type: "ServiceAreaMap", label: "Service Area", description: "ZIP codes and cities covered with a visual reference",          priority: "medium" },
    ],
    optionalPremiumSections: ["PressureWashRevealSection"],
    experimentalConcepts: [
      { id: "ProjectScopeQuiz",    concept: "Project Scope Quiz",         description: "Series of questions about the job (type, size, timeline, budget range) → outputs a written summary and contact form. Qualifies leads upfront."  },
      { id: "EstimateRangeWidget", concept: "Instant Estimate Range",     description: "Project type + rough dimensions → estimated cost range displayed immediately. Sets expectations and screens out low-budget inquiries."         },
      { id: "PortfolioShowcase",   concept: "Project Category Portfolio", description: "Gallery filtered by project type (kitchen, bath, deck, etc.) — shows breadth of work and helps customers see relevant examples."             },
    ],
    animationIdeas: [
      "Stat count-up: projects completed, years in trades",
      "Project card hover with shadow elevation for click affordance",
      "Hero with subtle parallax overlay on a clean project photo background",
    ],
    contentInputIdeas: [
      "Completed project photos (multiple project types)",
      "Before/after shots of renovations or repairs",
      "Crew or owner photo",
      "License and insurance certificate",
      "List of services and trade capabilities",
      "Service area cities/ZIP codes",
      "Any awards, review aggregator links, or association memberships",
    ],
    designNotes: "Straightforward, credible, professional. Customers want a contractor who communicates clearly and shows up. Design should feel organized and reliable — not flashy. Concrete project photography beats any abstract graphic. bold-contractor is the default style pack for maximum blue-collar credibility.",
    recommendedCustomModules: ["GalleryMasonry"],
    importantBusinessFields: ["businessName", "city", "serviceArea", "phone", "services"],
    mediaNeeds: ["completed project photos", "before/after", "crew on-site", "close-up of finished work details"],
    trustProofNeeds: ["licensed & insured", "years in trades", "projects completed", "service area"],
    ctaStrategy: "Free estimate. Make scope of work clear. Customers want to know you can handle their specific job.",
    quoteOrBookingNeeds: "Free estimate request: project type, timeline, address, brief description.",
    menuOrPricingNeeds: false,
    aiPromptNotes: "Straightforward, reliable, competent tone. Customers want a contractor who is clear about what they do, shows up when they say, and does quality work. Concrete, specific language over vague superlatives.",
    content: {
      heroHeadlineTemplate: "Quality Work. Honest Price. Done Right.",
      heroSubheadlineTemplate: "{businessName} — skilled trades for {area} homeowners and businesses. Licensed, insured, and ready.",
      heroCtaText: "Get a Free Estimate",
      heroBadgeTemplate: "Licensed & Insured · Serving {area}",
      servicesHeading: "What We Handle",
      servicesSubheadline: "Experienced across multiple trades. We tackle jobs others won't.",
      defaultServices: [
        { icon: "🔨", title: "Home Repairs",         description: "From small fixes to big repairs — we handle it all with the same care and quality."         },
        { icon: "🪟", title: "Installations",        description: "Doors, windows, fixtures, fans, and more — installed correctly the first time."             },
        { icon: "🪵", title: "Carpentry & Trim",     description: "Custom trim work, shelving, built-ins, and finish carpentry done to a professional standard."},
        { icon: "🧰", title: "Maintenance & Upkeep", description: "Seasonal maintenance, caulking, painting touch-ups, and the long list of to-dos."           },
      ],
      statsDefaults: [
        { value: "400+", label: "Projects Completed" },
        { value: "4.9★", label: "Client Rating"      },
        { value: "10+",  label: "Years in Trades"    },
        { value: "100%", label: "Licensed & Insured" },
      ],
      whyReasons: [
        { icon: "🔨", title: "Skilled Across Trades",   description: "We don't sub everything out. Our team handles most work in-house for quality control."    },
        { icon: "🛡️", title: "Licensed & Insured",     description: "Fully licensed and insured on every project. Your home and your investment are protected."  },
        { icon: "💬", title: "Clear Communication",     description: "You'll know what we're doing, why, and when. No changes without your approval."           },
        { icon: "🧹", title: "Respects Your Home",      description: "We protect your floors, clean up daily, and leave your space better than we found it."   },
        { icon: "📝", title: "Written Estimates",       description: "Every job starts with a written estimate you approve. No open-ended billing."             },
        { icon: "⏱️", title: "Meets Deadlines",         description: "We scope realistically and hit the timeline we commit to."                                },
      ],
      faqDefaults: [
        { question: "Are you licensed and insured?",                answer: "Yes — full licensing and liability insurance. We're happy to provide proof of insurance before work begins."                  },
        { question: "Do you handle small repairs or big projects?", answer: "Both. We take on everything from a single-day fix to multi-week renovations — if it's the right fit."                       },
        { question: "How do you price your work?",                  answer: "Most jobs are quoted at a fixed price after a site visit. We'll assess the scope and give you a written estimate."           },
        { question: "How do I get started?",                        answer: "Fill out our estimate form or give us a call. We'll schedule a site visit and send you a written proposal within 24 hours." },
      ],
      finalCtaHeading: "Ready to Get the Job Done Right?",
      finalCtaSubheading: "Get a free estimate from {businessName}. No pressure, no surprises — just honest, quality work.",
      finalCtaText: "Request Free Estimate",
    },
  },
];
